spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/skill_matching_userdb
spring.datasource.username=postgres
spring.datasource.password=admin37
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



# application.properties
#spring.security.enabled=false




