// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGP6evxQWvYyq0OwrOC6enJz5ZtzXOhZA',
    appId: '1:635699135026:web:0cbcdb3925ec6df24f322b',
    messagingSenderId: '635699135026',
    projectId: 'skillmatching-86b8d',
    authDomain: 'skillmatching-86b8d.firebaseapp.com',
    storageBucket: 'skillmatching-86b8d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhS-GlFg5PSijkzQEnRp7nFkFJZFOaNGs',
    appId: '1:635699135026:android:b053d764d55a4ebc4f322b',
    messagingSenderId: '635699135026',
    projectId: 'skillmatching-86b8d',
    storageBucket: 'skillmatching-86b8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_1t-4L6b0Cq6AAmMT9JH3fi1dMODkSJ8',
    appId: '1:635699135026:ios:589a5a1ca9b755a64f322b',
    messagingSenderId: '635699135026',
    projectId: 'skillmatching-86b8d',
    storageBucket: 'skillmatching-86b8d.firebasestorage.app',
    iosClientId: '635699135026-8u5sd0dupsdsrpc4kcb6rdtdhat7skcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillmatchFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_1t-4L6b0Cq6AAmMT9JH3fi1dMODkSJ8',
    appId: '1:635699135026:ios:589a5a1ca9b755a64f322b',
    messagingSenderId: '635699135026',
    projectId: 'skillmatching-86b8d',
    storageBucket: 'skillmatching-86b8d.firebasestorage.app',
    iosClientId: '635699135026-8u5sd0dupsdsrpc4kcb6rdtdhat7skcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillmatchFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGP6evxQWvYyq0OwrOC6enJz5ZtzXOhZA',
    appId: '1:635699135026:web:6e2dd4cc1fce04754f322b',
    messagingSenderId: '635699135026',
    projectId: 'skillmatching-86b8d',
    authDomain: 'skillmatching-86b8d.firebaseapp.com',
    storageBucket: 'skillmatching-86b8d.firebasestorage.app',
  );

}