spring:
  application:
    name: job-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${JOB_DB_NAME:job_service_db}${DB_PARAMS:?sslmode=disable}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
      group-id: job-service-group

firebase:
  credentials-path: ${FIREBASE_CREDENTIALS_PATH:classpath:firebase-credentials.json}

eureka:
  client:
    enabled: false

server:
  port: 8083
  servlet:
    context-path: /api/jobs